- name: Sever Configuration backend
  hosts: backend
  become: yes
  tasks: 
  - name: Disable nodejs 
    ansible.builtin.command: dnf module disable nodejs -y
    
  - name: Enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
    
  - name: Create a user
    ansible.builtin.user:
      name: expense
      state: present

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory
      mode: '755'