- name: Configure Mysql server
  hosts: mysql
  become: yes
  tasks: 
  - name: Install MySQL Server
    ansible.builtin.package:
      name: mysql-server
      state: installed
  
  - name: Start and Enable Mysql service
    service:
      name: mysql
      state: started
      enabled: yes